### ISSUE TITLE
NXEngine-evo

### ISSUE THREAD

**Issue by kquote03** [luong-komorebi/Awesome-Linux-Software#445]
NXEngine-evo is an "evolution" of NXEngine.
The project is listed here 
https://github.com/nxengine/nxengine-evo
It adds many things such as:
-Animated face pics
-Ability to customize soundtrack
-Widescreen support (essential)
-And much more coming soon !
It's available on the 3 major PC operating systems 
It can also be compiled to run on Haiku
And it's available as homebrew for HEN consoles (vita,switch,etc)
It doesn't make sense to add NXEngine and leave out NXEngine-evo

**Comment by luong-komorebi** [comment]
Hi @kenan1099, first  of all, I want to apologize if any thing listed here cause you disappointment.

As you may be aware of, NXEngine is available but NXEngine-evo is not. This is due to the following reasons:
1. I personally do not know NXEngine-evo's existence.
2. I personally do not add NXEngine. Another contributor suggested it, I tried it out then it got merged. 
3. This list is not about the best thing. The only case NXEngine Evo should be presented in place of NXEngine is when the original is discontinued, abandonned or have serious issues and no longer maintained, which is why these two can coexist in the list. 
With these points, I wonder if you can open a pull request and add NXEngine-evo to the list. Let me know if there is anything I can help you out.

**Comment by DimitrisPa** [comment]
Done #580
